twitter_clone/Users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name='Users'

urlpatterns=[
path('signup/',views.sign_up,name='signup'),
path('login/',auth_views.LoginView.as_view(template_name='Users/login.html'),name='login'),
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
path('following/',views.show_following,name='show_following'),
path('followers/',views.show_followers,name='show_followers'),
path('follow_the_user/<username>/',views.add_to_follows,name='add_to_follows'),
path('profile/<username>/',views.profile,name='profile'),
path('new_connections/',views.new_connections,name='new_connections'),
]

twitter_clone/tweet/urls.py
from django.urls import path,include
from . import views
app_name='tweet'

urlpatterns=[
path('create/',views.create_tweet,name='create_tweet'),
path('like_tweet_from_feed/<pk>/',views.like_tweet_from_feed,name='like_tweet_from_feed'),
path('like/<pk>/',views.like_tweet,name='like_tweet'),
path('comment_from_detail/<pk>/',views.comment_from_detail,name='comment_from_detail'),
path('delete/<pk>',views.delete_tweet,name='delete_tweet'),
path('comment_on_post/<pk>/',views.CommentOnPost.as_view(),name='comment_on_post'),
path('write_comment/<pk>/',views.write_comment,name='write_comment'),
path('recent_tweets/',views.recent_tweets,name='recent_tweets'),
]

twitter_clone/twitter_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from Users import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('Users.urls')),
    path('tweet/',include('tweet.urls')),
]

twitter_clone/Users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

def upload_to(instance, filename):
    return 'profile_pic/%s/%s' % (instance.user.username,filename)

class Profile(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    description=models.TextField(blank=True)
    profile_pic=models.ImageField(upload_to=upload_to,blank=True,default='profile_pic/None/no_image.jpg')

    def followers(self):
        return Follow.objects.filter(follows=self).count()
    def follower_count(self):
        return Follow.objects.filter(follows=self).count()

    def following(self):
        return Follow.objects.filter(user=self)

    def following_count(self):
        return Follow.objects.filter(user=self).count()

    def get_following_list(self):
        arr=[]
        follow_list=Follow.objects.all().filter(user=self)
        for obj in follow_list:
            arr.append(obj.follows)
        return arr 


    def __str__(self):
        return self.user.username


class Follow(models.Model):
    user=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='source')
    follows=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='destination')
    follow_date=models.DateTimeField(default=timezone.now())

    def __str__(self):
        return "{} follows {}".format(self.user.user.username,self.follows.user.username)

    class Meta:
        unique_together=('user','follows')

twitter_clone/Users/forms.py
from django import forms

class ProfileForm(forms.Form):
    username=forms.CharField(label='@username',max_length=100)
    password=forms.CharField(label='password',widget=forms.PasswordInput)
    first_name=forms.CharField(label='First Name',max_length=20)
    last_name=forms.CharField(label='Last Name',max_length=20)
    description=forms.CharField(label='Describe Yourself',widget=forms.Textarea(attrs={'rows':3, 'cols': 20}))
    profile_pic=forms.ImageField(label='Upload Profile Pic',required=False)

twitter_clone/Users/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from Users.forms import ProfileForm
from Users.models import Profile,Follow
from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.

def index(request):
    return render(request,'index.html')

def profile(request,**kwargs):
    name=kwargs['username']
    user=User.objects.get(username=name)
    profile_obj=Profile.objects.get(user=user)
    path=profile_obj.profile_pic.url
    follower_count=profile_obj.follower_count()
    following_count=profile_obj.following_count()
    return render(request,'Users/profile.html',{'profile':profile_obj,'path':path,'follower':follower_count,'following':following_count})

def show_followers(request):
    profile_obj=Profile.objects.get(user=request.user)
    follow_obj=Follow.objects.all().filter(follows=profile_obj).order_by('-follow_date')
    return render(request,'Users/show_followers.html',{'follower_obj':follow_obj})

def show_following(request):
    profile_obj=Profile.objects.get(user=request.user)
    following_obj=Follow.objects.all().filter(user = profile_obj).order_by('-follow_date')
    return render(request,'Users/show_following.html',{'following_obj':following_obj})

def new_connections(request):
    profile_obj=Profile.objects.get(user=request.user)
    arr=profile_obj.get_following_list()
    all_profiles=Profile.objects.all()
    new_list=[]
    for obj in all_profiles:
        if obj not in arr:
            new_list.append(obj)
    return render(request,'Users/new_connections.html',{'profiles':new_list})

def add_to_follows(request,**kwargs):
    user1=request.user
    user2=User.objects.get(username=kwargs['username'])
    p1=Profile.objects.get(user=user1)
    p2=Profile.objects.get(user=user2)
    follow_obj=Follow()
    follow_obj.user=p1
    follow_obj.follows=p2
    follow_obj.save()
    return HttpResponseRedirect(reverse('Users:new_connections'))


def sign_up(request):
    if request.method=="POST":
        form=ProfileForm(request.POST,request.FILES)
        username=request.POST['username']
        password=request.POST['password']
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        description=request.POST['description']
        user=User()
        user.username=username
        user.first_name=first_name
        user.last_name=last_name
        user.set_password(password)
        user.save()
        profile_obj=Profile()
        profile_obj.user=user
        if description:
            profile_obj.description=description
        if request.FILES.get('profile_pic'):
            profile_obj.profile_pic=request.FILES.get("profile_pic")
        profile_obj.save()
        return HttpResponseRedirect(reverse('index'))
    else:
        form=ProfileForm()
        return render(request,'Users/signup.html',{'form':form})

twitter_clone/templates/Users/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class='btn btn-default' value="Login">
  </form>
</div>
{% endblock %}

twitter_clone/templates/Users/new_connections.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="new_profiles">
  {% for profile in profiles %}
  <div class="single_profile">
    <div class="profile_image" style="float:left;">
      <i class="fas fa-user fa-4x" style="margin-left:10px;"></i>
    </div>
    <div class="profile_name">
      {{profile.user.username}}
    </div>
    {% if profile in profile.destination.all %}
    <div class="connection_button">
      <button type="button" name="button" class="btn btn-warning"><a href="{% url 'Users:add_to_follows' username=profile.user.username %}">Following</a></button>
    </div>
    {% else %}
    <div class="connection_button">
      <button type="button" name="button" class="btn btn-warning"><a href="{% url 'Users:add_to_follows' username=profile.user.username %}">Follow</a></button>
    </div>
    {% endif %}
  </div>
{% endfor %}
</div>
{% endblock %}

twitter_clone/templates/Users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Welcome @{{profile.user.username}}</h1>
{% if profile.user == user %}
<div class="profile_image image_fluid profile_icon">
  <i class="fas fa-users fa-4x"></i>
    <a href="{% url 'tweet:create_tweet' %}"><i class="fas fa-pen-alt fa-4x"></i></a>
</div>
{% endif %}
<div class="followes_following">
  <div>
      <span class="follow">Followers: {{follower}}</span> <a href="{% url 'Users:show_followers' %}">
        <button type="button" name="button" class="btn btn-sm btn-primary">Show</button></a>
  </div>
  <div>
      <span class="follow">Following: {{following}} <a href="{% url 'Users:show_following' %}">
        <button type="button" name="button" class="btn btn-sm btn-primary">Show</button></a>
  </div>
</div>
<h2 class="my_tweets_header">My Tweets:</h2>
{% for post in profile.tweets.all %}
<div class="my_tweets">
  <h4>{{post.message}}</h4>
  <span class="tweet_attributes"><a href="{% url 'tweet:like_tweet' pk=post.pk %}"><i class="fas fa-thumbs-up"></i></a>{{post.likes}}</span>
  <span class="tweet_attributes"><a href="{% url 'tweet:comment_on_post' pk=post.pk %}"><i class="fas fa-comment"></i></a>{{post.comments.count}}</span>
  {% if post.profile.user == user %}
  <span class="tweet_attributes"><a href="{% url 'tweet:delete_tweet' pk=post.pk %}" class="btn btn-warning btn-sm delete_tweet_button">Delete</a></span>
  {% endif %}
  <form class="comment_in_loop" action="{% url 'tweet:write_comment' pk=post.pk%}" method="post">
    {% csrf_token %}
    <input type="text" name="comment" placeholder="Write a comment">
    <input type="submit" value="Go" class="btn btn-sm btn-primary">
  </form>
</div>
{% endfor %}
{% endblock %}

twitter_clone/templates/Users/show_followers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="all_followers">
  {% for follower in follower_obj %}
  <div class="single_follower">
    {{follower.user.user.username}}
    <a href="{% url 'Users:profile' username=follower.user.user.username %}"><i class="far fa-user"></i></a>
    <div class="joined_together">
      Connected on : {{follower.follow_date}}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

twitter_clone/templates/Users/show_following.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="all_followering">
  {% for following in following_obj %}
  <div class="single_following">
    <div class="following_name">
        @{{following.follows.user.username}} <a href="{% url 'Users:profile' username=following.follows.user.username %}"><i class="far fa-user"></i></a>
    </div>
    <div class="joined_together">
      Connected on : {{following.follow_date}}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

twitter_clone/templates/Users/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container roboto">
  <h1>Sign Up</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create Account" class="btn btn-warning">
  </form>
</div>
{% endblock %}