twitter_clone/Users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name='Users'

urlpatterns=[
path('signup/',views.sign_up,name='signup'),
path('login/',auth_views.LoginView.as_view(template_name='Users/login.html'),name='login'),
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
path('following/',views.show_following,name='show_following'),
path('followers/',views.show_followers,name='show_followers'),
path('follow_the_user/<username>/',views.add_to_follows,name='add_to_follows'),
path('profile/<username>/',views.profile,name='profile'),
path('new_connections/',views.new_connections,name='new_connections'),
]

twitter_clone/tweet/urls.py
from django.urls import path,include
from . import views
app_name='tweet'

urlpatterns=[
path('create/',views.create_tweet,name='create_tweet'),
path('like_tweet_from_feed/<pk>/',views.like_tweet_from_feed,name='like_tweet_from_feed'),
path('like/<pk>/',views.like_tweet,name='like_tweet'),
path('comment_from_detail/<pk>/',views.comment_from_detail,name='comment_from_detail'),
path('delete/<pk>',views.delete_tweet,name='delete_tweet'),
path('comment_on_post/<pk>/',views.CommentOnPost.as_view(),name='comment_on_post'),
path('write_comment/<pk>/',views.write_comment,name='write_comment'),
path('recent_tweets/',views.recent_tweets,name='recent_tweets'),
]

twitter_clone/twitter_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from Users import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('Users.urls')),
    path('tweet/',include('tweet.urls')),
]

twitter_clone/tweet/models.py
from django.db import models
from Users.models import Profile
from django.utils import timezone
# Create your models here.

class Tweet(models.Model):
    profile=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='tweets')
    message=models.TextField(max_length=100)
    create_date=models.DateTimeField(default=timezone.now())
    likes=models.IntegerField(default=0)

    def __str__(self):
        return self.message



class Comment(models.Model):
    tweet=models.ForeignKey(Tweet,on_delete=models.CASCADE,related_name='comments')
    profile=models.ForeignKey(Profile,on_delete=models.CASCADE)
    comment=models.TextField(max_length=100)
    likes=models.IntegerField(default=0)

    def __str__(self):
        return self.comment

twitter_clone/tweet/forms.py
from django import forms

class CreateTweet(forms.Form):
    message=forms.CharField(label='',widget=forms.Textarea(attrs={'rows':3, 'cols': 20}))

twitter_clone/tweet/views.py
from django.shortcuts import render
from tweet.models import Tweet,Comment
from tweet.forms import CreateTweet
from Users.models import Profile,Follow
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views.generic.detail import DetailView
# Create your views here.

def create_tweet(request):
    if request.method=='POST':
        message=request.POST['message']
        profile_obj=Profile.objects.get(user=request.user)
        t_obj=Tweet()
        t_obj.profile=profile_obj
        t_obj.message=message
        t_obj.save()
        return HttpResponseRedirect(reverse('index'))
    else:
        form=CreateTweet()
        return render(request,'tweet/create_tweet.html',{'form':form})


def comment_from_detail(request,pk):
    tweet_obj=Tweet.objects.get(pk=pk)
    profile_obj=Profile.objects.get(user=request.user)
    comment_obj=Comment()
    comment_obj.tweet=tweet_obj
    comment_obj.profile=profile_obj
    comment_obj.comment=request.POST['comment']
    comment_obj.save()
    return HttpResponseRedirect(reverse('tweet:comment_on_post',kwargs={'pk':pk}))

def recent_tweets(request):
    profile_obj=Profile.objects.get(user=request.user)
    arr=profile_obj.get_following_list()
    tweets=Tweet.objects.all().filter(profile__in=arr).order_by('-create_date')
    return render(request,'tweet/recent_tweets.html',{'tweets':tweets})

def like_tweet_from_feed(request,pk):
    obj=Tweet.objects.get(pk=pk)
    obj.likes=obj.likes+1
    obj.save()
    return recent_tweets(request)

def like_tweet(request,pk):
    obj=Tweet.objects.get(pk=pk)
    obj.likes=obj.likes+1
    obj.save()
    return HttpResponseRedirect(reverse('Users:profile',kwargs={'username':request.user.username}))

def delete_tweet(request,pk):
    obj=Tweet.objects.get(pk=pk)
    obj.delete()
    return HttpResponseRedirect(reverse('Users:profile',kwargs={'username':request.user.username}))

class CommentOnPost(DetailView):
    template_name='tweet/comment_on_post.html'
    model=Tweet

def write_comment(request,pk):
    tweet_obj=Tweet.objects.get(pk=pk)
    profile_obj=Profile.objects.get(user=request.user)
    comment_obj=Comment()
    comment_obj.tweet=tweet_obj
    comment_obj.profile=profile_obj
    comment_obj.comment=request.POST['comment']
    comment_obj.save()
    return HttpResponseRedirect(reverse('Users:profile',kwargs={'username':request.user.username}))

twitter_clone/templates/tweet/comment_on_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>{{object.message}}</h2>
<div class="comment_on_post">
  {% for comment in object.comments.all %}
  <p> <a href="{% url 'Users:profile' username=comment.profile.user.username %}">@{{comment.profile.user.username}}</a>
  {{comment.comment}}</p>
  {% endfor %}
  <div class="comment_from_detail">
    <form action="{% url 'tweet:comment_from_detail' pk=object.pk %}" method="post">
      {% csrf_token %}
      <input type="text" name="comment" placeholder="Write a comment">
      <input type="submit" value="Go" class="btn btn-sm btn-primary">
    </form>
  </div>
</div>
{% endblock %}

twitter_clone/templates/tweet/create_tweet.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
  <h1>Tweet</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Tweet" class="btn btn-sm btn-primary">
  </form>
</div>
{% endblock %}

twitter_clone/templates/tweet/recent_tweets.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>All tweets</h3>
<div class="all_tweets">
  {% for tweet in tweets %}
  <div class="single_tweet">
    <div class="tweet_username">
      <a href="{% url 'Users:profile' username=tweet.profile.user.username %}">@{{tweet.profile.user.username}}</a>
    </div>
    <div class="written_date">
      {{tweet.create_date}}
    </div>
    <div class="tweet_text">
      {{tweet.message}}
    </div>
    <div class="other_attributes">
      <span><a href="{% url 'tweet:like_tweet_from_feed' pk=tweet.pk %}"><i class="fas fa-thumbs-up">{{tweet.likes}}</i></span>
      <span><a href="{% url 'tweet:comment_on_post' pk=tweet.pk %}"><i class="fas fa-comment"></i></a>{{tweet.comments.count}}</span>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}