twitter_clone/Users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name='Users'

urlpatterns=[
path('signup/',views.sign_up,name='signup'),
path('login/',auth_views.LoginView.as_view(template_name='Users/login.html'),name='login'),
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
path('following/',views.show_following,name='show_following'),
path('followers/',views.show_followers,name='show_followers'),
path('follow_the_user/<username>/',views.add_to_follows,name='add_to_follows'),
path('profile/<username>/',views.profile,name='profile'),
path('new_connections/',views.new_connections,name='new_connections'),
]

twitter_clone/tweet/urls.py
from django.urls import path,include
from . import views
app_name='tweet'

urlpatterns=[
path('create/',views.create_tweet,name='create_tweet'),
path('like_tweet_from_feed/<pk>/',views.like_tweet_from_feed,name='like_tweet_from_feed'),
path('like/<pk>/',views.like_tweet,name='like_tweet'),
path('comment_from_detail/<pk>/',views.comment_from_detail,name='comment_from_detail'),
path('delete/<pk>',views.delete_tweet,name='delete_tweet'),
path('comment_on_post/<pk>/',views.CommentOnPost.as_view(),name='comment_on_post'),
path('write_comment/<pk>/',views.write_comment,name='write_comment'),
path('recent_tweets/',views.recent_tweets,name='recent_tweets'),
]

twitter_clone/twitter_clone/urls.py
from django.contrib import admin
from django.urls import path,include
from Users import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('accounts/',include('Users.urls')),
    path('tweet/',include('tweet.urls')),
]

twitter_clone/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Twitter Clone</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@600&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'fontawesome-free-5.14.0-web/css/all.css' %}">
      <link rel="stylesheet" href="{% static 'css/new_name.css' %}">
      <style media="screen">
      </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id='navbar'>
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'index' %}">@twitter</a>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tweet:recent_tweets' %}">Feed</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Users:new_connections' %}">follow other friends</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tweet:create_tweet' %}">Tweet</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Users:profile' username=user.username %}">{{user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Users:logout' %}">LogOut</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Users:signup' %}">SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Users:login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
</body>
</html>

twitter_clone/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1 style="text-align:center;">Welcome to Twitter</h1>
{% endblock %}